### ISSUE TITLE
The indicated number on a tile is false

### ISSUE THREAD

**Issue by GregoirePeltier** [D10100111001/minesweeper_online#1]
While playing a revealed tile was not indicating what it should have 
[See picture here](https://imgur.com/a/zDu4R9d)

**Comment by D10100111001** [comment]
Looks fine to me as the mine with the x mark was a wrongly flagged tile.

**Comment by GregoirePeltier** [comment]
When the game is l tost he revealed tiles are the one clicked, and the one improperly flagged and no other ? 
( my bad if i just bothered you with an issue for not understanding the ui )
